In [1]:
# from selenium import webdriver
# from selenium.webdriver.common.by import By
# from selenium.webdriver.support.ui import WebDriverWait
# from selenium.webdriver.support import expected_conditions as EC
# from selenium.webdriver.chrome.service import Service
# from webdriver_manager.chrome import ChromeDriverManager
# import pandas as pd
# import time

# # Настройка WebDriver
# service = Service(ChromeDriverManager().install())
# driver = webdriver.Chrome(service=service)

# # Список для хранения текстов песен
# data = []

# try:
#     # URL страницы артиста
#     artist_url = "https://genius.com/artists/Slava-kpss/songs"
#     driver.get(artist_url)

#     # Прокрутка страницы до конца, чтобы загрузить все песни
#     last_height = driver.execute_script("return document.body.scrollHeight")
#     while True:
#         driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
#         time.sleep(3)  # Даем время на подгрузку
#         new_height = driver.execute_script("return document.body.scrollHeight")
#         if new_height == last_height:
#             break
#         last_height = new_height

#     # Находим все карточки песен
#     # Поиск по CSS-селектору
#     song_links = []
#     songs = driver.find_elements(By.CSS_SELECTOR, "a.ListItem-sc-4f1bc3d5-1.kqeBAm")
#     for song in songs:
#         link = song.get_attribute("href")
#         song_links.append(link)
#     print(f"Найдено {len(song_links)} песен")

#     # Проход по всем песням
#     for index, link in enumerate(song_links):
#         try:
#             print(f"Обрабатываем песню {index+1}: {link}")

#             # Переход на страницу песни
#             driver.get(link)
#             time.sleep(3)

#             # Получение названия песни
#             title = WebDriverWait(driver, 10).until(
#                 EC.presence_of_element_located((By.CSS_SELECTOR, 'span[class^="SongHeader-desktop"]'))
#             ).text

#             # Получение текста песни
#             try:
#                 lyrics_element = WebDriverWait(driver, 10).until(
#                     EC.presence_of_element_located((By.CSS_SELECTOR, 'div[data-lyrics-container="true"]'))
#                 )
#                 lyrics = lyrics_element.text
#             except:
#                 lyrics = "Текст не найден"

#             # Сохранение данных
#             data.append({"title": title, "lyrics": lyrics, "link": link})
#             print(f"Песня '{title}' добавлена.")

#         except Exception as e:
#             print(f"Ошибка при обработке песни {index+1}: {e}")

# finally:
#     # Закрываем драйвер
#     driver.quit()

# # Сохранение данных в DataFrame и экспорт в CSV
# df = pd.DataFrame(data)
# df.to_csv("slava_kpss_lyrics.csv", index=False)
# print("Сбор данных завершен. Результат сохранен в slava_kpss_lyrics.csv")

In [2]:
 import pandas as pd

In [3]:
df = pd.read_csv('slava_kpss_lyrics.csv')

In [4]:
df.shape

(1263, 3)

In [5]:
df.head(2)

,title,lyrics,link
0,13/08/17: Oxxxymiron vs. Слава КПСС,"[Раунд 1: Oxxxymiron]\nЯ здесь чисто по фану, ...",https://genius.com/Versus-battle-13-08-17-oxxx...
1,07/07/16: Edik_Kingsta vs. Соня Мармеладова,[Раунд 1 (часть 1): Соня Мармеладова]\nВ тебе ...,https://genius.com/140-bpm-battle-07-07-16-edi...

In [6]:
df['lyrics'][129]

'[Текст песни "Егор Летов"]\n\n[Интро]\nЙоу, я единственный заслуживаю этого здания, лошки\n(Этого звания)\nЙе, йе, йе\n\n[Припев]\nЯ Егор Летов (У, эй)\nЯ Егор Летов (У, эй)\nЯ Егор Летов (У, эй)\nЯ Егор Летов, я Егор Летов\nЯ Егор Летов (У, эй)\nЯ Егор Летов (У, эй)\nЯ Егор Летов (У, эй)\nЯ Егор Летов, я Егор Летов\n\n[Бридж]\nРусское поле экспериментов\n(В джазе это называется «Новая романтика»)\nРусское поле экспериментов\n(То, что мы сейчас сделаем — своего рода метамодерн)\n\n[Припев]\n(Brrr)\nЯ Егор Летов (У, эй)\nЯ Егор Летов (У, эй)\nЯ Егор Летов (У, эй)\nЯ Егор Летов, я Егор Летов\nЯ Егор Летов (У, эй)\nЯ Егор Летов (У, эй)\nЯ Егор Летов (У, эй)\nЯ Егор Летов, я Егор Летов'

In [7]:
import re
def remove_bracketed_sections(text):
    # Удаляет все текстовые секции, заключенные в квадратные скобки, из текста.
    text = re.sub(r'\[.*?\]', '', text)
    # Создает таблицу перевода для замены определенных символов
    translation_table = str.maketrans({';': '', '"': '', ' ': ' '})
    # Применяет таблицу перевода к тексту, заменяя указанные символы на пробелы.
    return text.translate(translation_table)

In [8]:
df['lyrics'] = df['lyrics'].apply(remove_bracketed_sections)

In [9]:
df['lyrics'][129]

'\n\n\nЙоу, я единственный заслуживаю этого здания, лошки\n(Этого звания)\nЙе, йе, йе\n\n\nЯ Егор Летов (У, эй)\nЯ Егор Летов (У, эй)\nЯ Егор Летов (У, эй)\nЯ Егор Летов, я Егор Летов\nЯ Егор Летов (У, эй)\nЯ Егор Летов (У, эй)\nЯ Егор Летов (У, эй)\nЯ Егор Летов, я Егор Летов\n\n\nРусское поле экспериментов\n(В джазе это называется «Новая романтика»)\nРусское поле экспериментов\n(То, что мы сейчас сделаем — своего рода метамодерн)\n\n\n(Brrr)\nЯ Егор Летов (У, эй)\nЯ Егор Летов (У, эй)\nЯ Егор Летов (У, эй)\nЯ Егор Летов, я Егор Летов\nЯ Егор Летов (У, эй)\nЯ Егор Летов (У, эй)\nЯ Егор Летов (У, эй)\nЯ Егор Летов, я Егор Летов'

In [10]:
def preprocess_lyrics(text):
    # Убираем тройные переводы строк
    text = re.sub(r'\n{2,}', '\n', text)
    text = re.sub(r'\(.*?\)', '', text)
    # Убираем лишние пробелы и пустые строки
    text = re.sub(r'\s*\n\s*', '\n', text)  # Убираем пробелы вокруг переносов строк
    # Убираем начальные и конечные пробелы
    text = text.strip()
    return text

In [11]:
df['lyrics'] = df['lyrics'].apply(preprocess_lyrics)
df['lyrics'][129]

'Йоу, я единственный заслуживаю этого здания, лошки\nЙе, йе, йе\nЯ Егор Летов\nЯ Егор Летов\nЯ Егор Летов\nЯ Егор Летов, я Егор Летов\nЯ Егор Летов\nЯ Егор Летов\nЯ Егор Летов\nЯ Егор Летов, я Егор Летов\nРусское поле экспериментов\nРусское поле экспериментов\nЯ Егор Летов\nЯ Егор Летов\nЯ Егор Летов\nЯ Егор Летов, я Егор Летов\nЯ Егор Летов\nЯ Егор Летов\nЯ Егор Летов\nЯ Егор Летов, я Егор Летов'

In [12]:
all_songs = "\n\n".join(df['lyrics'].dropna())
with open("all_songs.txt", "w", encoding="utf-8") as f:
    f.write(all_songs)

In [13]:
from transformers import GPT2LMHeadModel, Trainer, TrainingArguments
from datasets import Dataset
from transformers import GPT2Tokenizer

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token  # Используем eos_token в качестве pad_token

# Сохранение обновленного токенизатора
tokenizer.save_pretrained('./tokenizer/')

# Загружаем модель
model = GPT2LMHeadModel.from_pretrained("gpt2")

# Создание датасета
dataset = Dataset.from_dict({"text": [all_songs]})

def tokenize_function(examples):
    tokens = tokenizer(
        examples["text"],
        truncation=True,
        padding="max_length",
        max_length=512,
    )
    # Добавляем метки, которые совпадают с input_ids
    tokens["labels"] = tokens["input_ids"].copy()
    return tokens


tokenized_dataset = dataset.map(tokenize_function, batched=True)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Map:   0%|          | 0/1 [00:00<?, ? examples/s]

In [14]:
# from transformers import Trainer, TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=3,
    per_device_train_batch_size=2,
    save_steps=10_000,
    save_total_limit=2,
    prediction_loss_only=False,  # Включаем расчёт потерь
    logging_dir='./logs',
    report_to=[],
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
)

In [15]:
trainer.train()
# Сохранение обученной модели
trainer.save_model("./results")  # Сохраняет модель и её конфигурацию
tokenizer.save_pretrained("./results")  # Сохраняет токенизатор

('./results/tokenizer_config.json',
 './results/special_tokens_map.json',
 './results/vocab.json',
 './results/merges.txt',
 './results/added_tokens.json')

In [16]:
model = GPT2LMHeadModel.from_pretrained("./results")
tokenizer = GPT2Tokenizer.from_pretrained("./tokenizer")
model.eval()

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2SdpaAttention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)

In [17]:
from transformers import TextGenerationPipeline

generator = TextGenerationPipeline(model=model, tokenizer=tokenizer)
def generate_text(prompt, max_length=100, num_return_sequences=1):
  results = generator(
        prompt,
        max_length=max_length,
        num_return_sequences=num_return_sequences,
        do_sample=True,  # Включает семплирование для более разнообразных результатов
        temperature=0.7,  # Управляет "творческой свободой" генерации (меньше - более детерминированно)
        top_k=50,  # Учитывает только топ-50 вероятных слов
        top_p=0.95,  # Nucleus Sampling, учитывает слова с вероятностью до 95%
    )
  return [result["generated_text"] for result in results]

In [20]:
# Пример начального текста
prompt = "Курить и сдохнуть, схвативши оголённый провод как дружеский локоть"

# Генерация текста
generated_texts = generate_text(prompt, max_length=200, num_return_sequences=1)

# Печать результатов
for idx, text in enumerate(generated_texts, 1):
    print(f"Сгенерированный текст {idx}:\n{text}\n")

Сгенерированный текст 1:
Курить и сдохнуть, схвативши оголённый провод как дружеский локоть мопростой выму в продбовей покак дайтельный сельшемы провод свосты честву на и серний в кономанный, стайты дайти �